language: java

matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk8
      script:
        - pip install pygments

    - os: osx
      osx_image: xcode9.3
      jdk: oraclejdk8
      script:
        - pip install pygments