os: osx
osx_image: xcode10.1

language: cpp

install:
  - echo "Hello World!" >> artifact.txt

script:
  - export TRAVIS_TAG="${TRAVIS_BRANCH}-tag"
  - export TRAVIS_COMMIT_MESSAGE="Message ${TRAVIS_COMMIT_MESSAGE} https://github.com"

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file:
    - artifact.txt
  overwrite: true
  skip_cleanup: true
  on:
    repo: robert-schmidtke/travis-test
    tags: true