os: osx
osx_image: xcode10.1

language: cpp

if: tag IS blank

install:
  - echo "Hello World!" >> artifact.txt

script:
  - export TRAVIS_TAG="${TRAVIS_BRANCH}-tag"

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file:
    - artifact.txt
  name: "https://github.com"
  body: "https://github.com"
  overwrite: true
  skip_cleanup: true
  on:
    repo: robert-schmidtke/travis-test
    tags: true