os: osx
osx_image: xcode10.1

language: cpp

install:
  - echo "Hello World!" >> artifact.txt

script: skip

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_BRANCH}

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: artifact.txt
  overwrite: true
  skip_cleanup: true
  on:
    repo: robert-schmidtke/travis-test
