os: osx
osx_image: xcode10.1

language: cpp

install:
  - touch artifact.txt

script: skip

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_BRANCH}
  - echo ${ENCRYPTED_GITHUB_OAUTH_TOKEN}

deploy:
  provider: releases
  api_key: ${ENCRYPTED_GITHUB_OAUTH_TOKEN}
  on:
    repo: robert-schmidtke/travis-test
