os: osx
osx_image: xcode10.1

language: cpp

script:
  - env
  - ls -al ${HOME}
  - ls -al ${HOME}/.gnupg
  - ls -al ${HOME}/.gnupg/private-keys-v1.d
  - ls -al ${HOME}/.ssh
  - gpg --list-keys
  - ls -al ${TRAVIS_BUILD_DIR}
  - find ${HOME}/build
  - find ${TMPDIR}
  - sleep 30s
